from isam import Isam, Page, Node
estructura = Isam()
estructura.root = Page()
estructura.leftmost = estructura.root
estructura.root.leaf = True
estructura.height = 0
estructura.root.insert(Node([30, "Juan", "Ortiz", "Su casa"]), estructura.full)
estructura.root.insert(Node([50, "Angelica", "Godoy", "Su casa"]), estructura.full)
estructura.draw()

estructura0 = Isam()
estructura0.root = Page()
estructura0.leftmost = estructura0.root
estructura0.root.leaf = True
estructura0.height = 0
estructura0.root.insert(Node([30, "Juan", "Ortiz", "Su casa"]), estructura0.full)
estructura0.root.insert(Node([50, "Angelica", "Godoy", "Su casa"]), estructura0.full)
estructura0.procreate()
estructura0.root.right.insert(Node([60, "Juana", "López", "Su casa"]), estructura0.full)
estructura0.update_level(0)
estructura0.draw()

estructura1 = Isam()
estructura1.root = Page()
estructura1.leftmost = estructura1.root
estructura1.root.leaf = True
estructura1.height = 0
estructura1.root.insert(Node([30, "Juan", "Ortiz", "Su casa"]), estructura1.full)
estructura1.root.insert(Node([50, "Angelica", "Godoy", "Su casa"]), estructura1.full)
estructura1.procreate()
estructura1.root.mid.insert(Node([40, "Fernando", "Martínez", "Su casa"]), estructura1.full)
estructura1.root.left.insert(Node([20, "Luis", "López", "Su casa"]), estructura1.full)
estructura1.root.right.insert(Node([60, "Juana", "López", "Su casa"]), estructura1.full)
estructura1.root.right.insert(Node([70, "Lucía", "Fernández", "Su casa"]), estructura1.full)
estructura1.update_level(0)
estructura1.procreate()
estructura1.root.left.right.insert(Node([35, "Ana", "Pineda", "Su casa"]), estructura1.full)
estructura1.update_level(1)
estructura1.update_level(0)
estructura1.draw()

estructura2 = Isam()
estructura2.root = Page()
estructura2.leftmost = estructura2.root
estructura2.root.leaf = True
estructura2.height = 0
estructura2.root.insert(Node([30, "Juan", "Ortiz", "Su casa"]), estructura2.full)
estructura2.root.insert(Node([50, "Angelica", "Godoy", "Su casa"]), estructura2.full)
estructura2.procreate()
estructura2.root.mid.insert(Node([40, "Fernando", "Martínez", "Su casa"]), estructura2.full)
estructura2.root.left.insert(Node([20, "Luis", "López", "Su casa"]), estructura2.full)
estructura2.root.right.insert(Node([60, "Juana", "López", "Su casa"]), estructura2.full)
estructura2.root.right.insert(Node([70, "Lucía", "Fernández", "Su casa"]), estructura2.full)
estructura2.update_level(0)
estructura2.procreate()
estructura2.root.left.right.insert(Node([35, "Ana", "Pineda", "Su casa"]), estructura2.full)
estructura2.root.mid.right.insert(Node([55, "Francisco", "Gómez", "Su casa"]), estructura2.full)
estructura2.root.right.right.insert(Node([80, "Francisco", "Perea", "Su casa"]), estructura2.full)
estructura2.update_level(1)
estructura2.update_level(0)
estructura2.draw()

estructura3 = Isam()
estructura3.root = Page()
estructura3.leftmost = estructura3.root
estructura3.root.leaf = True
estructura3.height = 0
estructura3.root.insert(Node([30, "Juan", "Ortiz", "Su casa"]), estructura3.full)
estructura3.root.insert(Node([50, "Angelica", "Godoy", "Su casa"]), estructura3.full)
estructura3.procreate()
estructura3.root.mid.insert(Node([40, "Fernando", "Martínez", "Su casa"]), estructura3.full)
estructura3.root.left.insert(Node([20, "Luis", "López", "Su casa"]), estructura3.full)
estructura3.root.right.insert(Node([60, "Juana", "López", "Su casa"]), estructura3.full)
estructura3.root.right.insert(Node([70, "Lucía", "Fernández", "Su casa"]), estructura3.full)
estructura3.update_level(0)
estructura3.procreate()
estructura3.root.left.right.insert(Node([35, "Ana", "Pineda", "Su casa"]), estructura3.full)
estructura3.root.mid.right.insert(Node([55, "Francisco", "Gómez", "Su casa"]), estructura3.full)
estructura3.root.right.right.insert(Node([80, "Francisco", "Perea", "Su casa"]), estructura3.full)
estructura3.root.left.left.insert(Node([25, "Mario", "Azurdia", "Su casa"]), estructura3.full)
estructura3.root.left.mid.insert(Node([33, "Manuel", "Pérez", "Su casa"]), estructura3.full)
estructura3.root.left.right.insert(Node([37, "Kevin", "Muñoz", "Su casa"]), estructura3.full)
estructura3.root.mid.left.insert(Node([45, "Antonio", "Pérez", "Su casa"]), estructura3.full)
estructura3.root.mid.mid.insert(Node([53, "Luisa", "Martínez", "Su casa"]), estructura3.full)
estructura3.root.mid.right.insert(Node([57, "Cornelio", "Marroquín", "Su casa"]), estructura3.full)
estructura3.root.right.left.insert(Node([65, "Lorena", "Martínez", "Su casa"]), estructura3.full)
estructura3.root.right.mid.insert(Node([75, "Ambrosio", "Saucedo", "Su casa"]), estructura3.full)
estructura3.root.right.right.insert(Node([85, "Alfonso", "Fernández", "Su casa"]), estructura3.full)
estructura3.update_level(1)
estructura3.update_level(0)
estructura3.draw()

estructura4 = Isam()
estructura4.root = Page()
estructura4.leftmost = estructura4.root
estructura4.root.leaf = True
estructura4.height = 0
estructura4.root.insert(Node([30, "Juan", "Ortiz", "Su casa"]), estructura4.full)
estructura4.root.insert(Node([50, "Angelica", "Godoy", "Su casa"]), estructura4.full)
estructura4.procreate()
estructura4.root.mid.insert(Node([40, "Fernando", "Martínez", "Su casa"]), estructura4.full)
estructura4.root.left.insert(Node([20, "Luis", "López", "Su casa"]), estructura4.full)
estructura4.root.right.insert(Node([60, "Juana", "López", "Su casa"]), estructura4.full)
estructura4.root.right.insert(Node([70, "Lucía", "Fernández", "Su casa"]), estructura4.full)
estructura4.update_level(0)
estructura4.procreate()
estructura4.root.left.right.insert(Node([35, "Ana", "Pineda", "Su casa"]), estructura4.full)
estructura4.root.mid.right.insert(Node([55, "Francisco", "Gómez", "Su casa"]), estructura4.full)
estructura4.root.right.right.insert(Node([80, "Francisco", "Perea", "Su casa"]), estructura4.full)
estructura4.root.left.left.insert(Node([25, "Mario", "Azurdia", "Su casa"]), estructura4.full)
estructura4.root.left.mid.insert(Node([33, "Manuel", "Pérez", "Su casa"]), estructura4.full)
estructura4.root.left.right.insert(Node([37, "Kevin", "Muñoz", "Su casa"]), estructura4.full)
estructura4.root.mid.left.insert(Node([45, "Antonio", "Pérez", "Su casa"]), estructura4.full)
estructura4.root.mid.mid.insert(Node([53, "Luisa", "Martínez", "Su casa"]), estructura4.full)
estructura4.root.mid.right.insert(Node([57, "Cornelio", "Marroquín", "Su casa"]), estructura4.full)
estructura4.root.right.left.insert(Node([65, "Lorena", "Martínez", "Su casa"]), estructura4.full)
estructura4.root.right.mid.insert(Node([75, "Ambrosio", "Saucedo", "Su casa"]), estructura4.full)
estructura4.root.right.right.insert(Node([85, "Alfonso", "Fernández", "Su casa"]), estructura4.full)
estructura4.root.mid.mid.insert(Node([52, "Gretel", "Ramos", "Su casa"]), estructura4.full)
estructura4.root.mid.mid.insert(Node([51, "Gabriel", "Ramos", "Su casa"]), estructura4.full)
estructura4.root.mid.left.insert(Node([43, "Karla", "Gómez", "Su casa"]), estructura4.full)
estructura4.root.mid.left.insert(Node([41, "Andrea", "Pineda", "Su casa"]), estructura4.full)
estructura4.root.mid.left.insert(Node([42, "Martina", "Pineda", "Su casa"]), estructura4.full)
estructura4.root.mid.left.insert(Node([44, "Luciano", "Pineda", "Su casa"]), estructura4.full)
estructura4.root.left.left.insert(Node([24, "Rufino", "Morales", "Su casa"]), estructura4.full)
estructura4.root.left.left.insert(Node([22, "Rafael", "Mejicanos", "Su casa"]), estructura4.full)
estructura4.root.left.left.insert(Node([21, "Rigoberto", "Giron", "Su casa"]), estructura4.full)
estructura4.update_level(1)
estructura4.update_level(0)
estructura4.draw()