import storageManager as sm

sm.createDatabase("database1", "avl", "utf8")
sm.createDatabase("database2", "b", "utf8")
sm.createDatabase("database3", "bplus", "utf8")
sm.createDatabase("database4", "hash", "utf8")
sm.createDatabase("database5", "isam", "utf8")
sm.createDatabase("database6", "dict", "utf8")
sm.createDatabase("database7", "json", "utf8")

sm.createTable("database1", "table1", 3)

sm.createTable("database2", "table1", 3)
sm.createTable("database2", "table2", 3)

sm.createTable("database3", "table1", 3)
sm.createTable("database3", "table2", 3)
sm.createTable("database3", "table3", 3)

sm.createTable("database4", "table1", 3)
sm.createTable("database4", "table2", 3)
sm.createTable("database4", "table3", 3)
sm.createTable("database4", "table4", 3)

sm.createTable("database5", "table1", 3)
sm.createTable("database5", "table2", 3)
sm.createTable("database5", "table3", 3)
sm.createTable("database5", "table4", 3)
sm.createTable("database5", "table5", 3)

sm.createTable("database6", "table1", 3)
sm.createTable("database6", "table2", 3)
sm.createTable("database6", "table3", 3)
sm.createTable("database6", "table4", 3)
sm.createTable("database6", "table5", 3)
sm.createTable("database6", "table6", 3)

sm.createTable("database7", "table1", 3)
sm.createTable("database7", "table2", 3)
sm.createTable("database7", "table3", 3)
sm.createTable("database7", "table4", 3)
sm.createTable("database7", "table5", 3)
sm.createTable("database7", "table6", 3)
sm.createTable("database7", "table7", 3)

sm.alterAddPK("database1", "table1", [0])
sm.alterAddPK("database2", "table1", [0])
sm.alterAddPK("database3", "table1", [0])
sm.alterAddPK("database4", "table1", [0])
sm.alterAddPK("database5", "table1", [0])
sm.alterAddPK("database6", "table1", [0])
sm.alterAddPK("database7", "table1", [0])

sm.loadCSV("./registros.csv", "database1", "table1")
sm.loadCSV("./registros.csv", "database2", "table1")
sm.loadCSV("./registros.csv", "database3", "table1")
sm.loadCSV("./registros.csv", "database4", "table1")
sm.loadCSV("./registros.csv", "database5", "table1")
sm.loadCSV("./registros.csv", "database6", "table1")
sm.loadCSV("./registros.csv", "database7", "table1")

sm.alterTableMode("database1", "table1", "hash")
sm.alterTableMode("database2", "table1", "hash")
sm.alterTableMode("database3", "table1", "hash")
sm.alterTableMode("database4", "table1", "hash")
#sm.alterTableMode("database5", "table1", "hash")
sm.alterTableMode("database6", "table1", "hash")
sm.alterTableMode("database7", "table1", "hash")

sm.alterDatabaseMode("database1", "avl")
sm.alterDatabaseMode("database2", "b")
sm.alterDatabaseMode("database3", "bplus")
sm.alterDatabaseMode("database4", "hash")
sm.alterDatabaseMode("database5", "isam")
sm.alterDatabaseMode("database6", "dict")
sm.alterDatabaseMode("database7", "json")


sm.databases.show()
sm.alterDatabaseMode("database1", "hash")
sm.alterDatabaseMode("database4", "avl")

#extractTable():
# sm.extractTable("database1","table1")
# sm.extractTable("database2","table1")
# sm.extractTable("database3","table4")
# sm.extractTable("database4","table2")
# sm.extractTable("database5","table2")
# sm.extractTable("database6","table3")
# sm.extractTable("database7","table3")

#extractRangeTable("calificacion",'hiddenPK',0,'Andree','Andree')
# extractRangeTable("database1","table1", 3, lower, upper)
# extractRangeTable("database2","table2", 3, lower, upper)
# extractRangeTable("database3","table3", 3, lower, upper)
# extractRangeTable("database4","table4", 3, lower, upper)
# extractRangeTable("database5","table5", 3, lower, upper)
# extractRangeTable("database6","table6", 3, lower, upper)
# extractRangeTable("database7","table7", 3, lower, upper)

#alterTable()
# sm.alterTable("database2","table2",'table_2')
# sm.alterTable("database3","table1",'tab1')
# sm.alterTable("database1","table1",'tab1')
# sm.alterTable("database4","table4",'tab4')
# sm.alterTable("database5","table5",'tab5')#problema2
# sm.alterTable("database5","table3",'tab3')#problema2
# sm.alterTable("database6","table5",'tab5')
# sm.alterTable("database7","table5",'tab5')
# print(sm.showDatabases())
# print("tablas database2:",sm.showTables("database2"))
# print("tablas database3:",sm.showTables("database3"))
# print("tablas database1:",sm.showTables("database1"))
# print("tablas database4:",sm.showTables("database4"))
# print("tablas database5:",sm.showTables("database5"))#--prob2
# print("tablas database6:",sm.showTables("database6"))
# print("tablas database7:",sm.showTables("database7"))

# #dropTable()
# print("-----dropTable()------")
# sm.dropTable('database1','tab1')
# sm.dropTable('database2','table_2')
# sm.dropTable('database3','tab1')
# sm.dropTable('database4','tab4')
# sm.dropTable('database5','table2')#problema3
# sm.dropTable('database6','table2')
# sm.dropTable('database7','table1')
# sm.dropTable('database7','table2')
# print(sm.showDatabases())
# print("tablas database1:",sm.showTables("database1"))
# print("tablas database2:",sm.showTables("database2"))
# print("tablas database3:",sm.showTables("database3"))
# print("tablas database4:",sm.showTables("database4"))
# print("tablas database5:",sm.showTables("database5"))
# print("tablas database6:",sm.showTables("database6"))
# print("tablas database7:",sm.showTables("database7"))

# #extractRow()
# print("-----extractRow()------")
# sm.extractRow('database1','tab1', columns)
# sm.extractRow(database, table, columns)
# sm.extractRow(database, table, columns)
# sm.extractRow(database, table, columns)
# sm.extractRow(database, table, columns)
# sm.extractRow(database, table, columns)
# sm.extractRow(database, table, columns)
# sm.extractRow(database, table, columns)
# sm.extractRow(database, table, columns)
# j.extractRow('calificacion','loadCSV',[42663506])

#alterAddPK()

# sm.alterAddPK('database1','tab1',[])
# sm.alterAddPK('database2','table1',[])
# sm.alterAddPK('database3','table3',[])
# sm.alterAddPK('database4','table3',[])
# sm.alterAddPK('database5','table5',[])
# sm.alterAddPK('database6','table6',[])
# sm.alterAddPK('database7','table7',[])


#truncate()
# sm.dropTable('database1','tab1')
# sm.dropTable('database2','table_2')
# sm.dropTable('database3','table3')
# sm.dropTable('database4','table4')
# sm.dropTable('database5','table5')
# sm.dropTable('database6','table6')
# sm.dropTable('database7','table7')
