import storageManager

storageManager.createDatabase("database1", "avl", "utf8")
storageManager.createDatabase("database2", "b", "utf8")
storageManager.createDatabase("database3", "bplus", "utf8")
storageManager.createDatabase("database4", "hash", "utf8")
storageManager.createDatabase("database5", "isam", "utf8")
storageManager.createDatabase("database6", "dict", "utf8")
storageManager.createDatabase("database7", "json", "utf8")

storageManager.createTable("database1", "table1", 3)

storageManager.createTable("database2", "table1", 3)
storageManager.createTable("database2", "table2", 3)

storageManager.createTable("database3", "table1", 3)
storageManager.createTable("database3", "table2", 3)
storageManager.createTable("database3", "table3", 3)

storageManager.createTable("database4", "table1", 3)
storageManager.createTable("database4", "table2", 3)
storageManager.createTable("database4", "table3", 3)
storageManager.createTable("database4", "table4", 3)

storageManager.createTable("database5", "table1", 3)
storageManager.createTable("database5", "table2", 3)
storageManager.createTable("database5", "table3", 3)
storageManager.createTable("database5", "table4", 3)
storageManager.createTable("database5", "table5", 3)

storageManager.createTable("database6", "table1", 3)
storageManager.createTable("database6", "table2", 3)
storageManager.createTable("database6", "table3", 3)
storageManager.createTable("database6", "table4", 3)
storageManager.createTable("database6", "table5", 3)
storageManager.createTable("database6", "table6", 3)

storageManager.createTable("database7", "table1", 3)
storageManager.createTable("database7", "table2", 3)
storageManager.createTable("database7", "table3", 3)
storageManager.createTable("database7", "table4", 3)
storageManager.createTable("database7", "table5", 3)
storageManager.createTable("database7", "table6", 3)
storageManager.createTable("database7", "table7", 3)

#extractTable():
# storageManager.extractTable("database1","table1")
# storageManager.extractTable("database2","table1")
# storageManager.extractTable("database3","table4")
# storageManager.extractTable("database4","table2")
# storageManager.extractTable("database5","table2")
# storageManager.extractTable("database6","table3")
# storageManager.extractTable("database7","table3")

#extractRangeTable("calificacion",'hiddenPK',0,'Andree','Andree')
# extractRangeTable("database1","table1", 3, lower, upper)
# extractRangeTable("database2","table2", 3, lower, upper)
# extractRangeTable("database3","table3", 3, lower, upper)
# extractRangeTable("database4","table4", 3, lower, upper)
# extractRangeTable("database5","table5", 3, lower, upper)
# extractRangeTable("database6","table6", 3, lower, upper)
# extractRangeTable("database7","table7", 3, lower, upper)

#alterTable()
storageManager.alterTable("database2","table2",'table_2')
storageManager.alterTable("database3","table1",'tab1')
storageManager.alterTable("database1","table1",'tab1')
storageManager.alterTable("database4","table4",'tab4')
storageManager.alterTable("database5","table5",'tab5')#problema2
storageManager.alterTable("database5","table3",'tab3')#problema2
storageManager.alterTable("database6","table5",'tab5')
storageManager.alterTable("database7","table5",'tab5')
print(storageManager.showDatabases())
print("tablas database2:",storageManager.showTables("database2"))
print("tablas database3:",storageManager.showTables("database3"))
print("tablas database1:",storageManager.showTables("database1"))
print("tablas database4:",storageManager.showTables("database4"))
print("tablas database5:",storageManager.showTables("database5"))#--prob2
print("tablas database6:",storageManager.showTables("database6"))
print("tablas database7:",storageManager.showTables("database7"))

#dropTable()
print("-----dropTable()------")
storageManager.dropTable('database1','tab1')
storageManager.dropTable('database2','table_2')
storageManager.dropTable('database3','tab1')
storageManager.dropTable('database4','tab4')
storageManager.dropTable('database5','table2')#problema3
storageManager.dropTable('database6','table2')
storageManager.dropTable('database7','table1')
storageManager.dropTable('database7','table2')
print(storageManager.showDatabases())
print("tablas database1:",storageManager.showTables("database1"))
print("tablas database2:",storageManager.showTables("database2"))
print("tablas database3:",storageManager.showTables("database3"))
print("tablas database4:",storageManager.showTables("database4"))
print("tablas database5:",storageManager.showTables("database5"))
print("tablas database6:",storageManager.showTables("database6"))
print("tablas database7:",storageManager.showTables("database7"))

# #extractRow()
# print("-----extractRow()------")
# storageManager.extractRow('database1','tab1', columns)
# storageManager.extractRow(database, table, columns)
# storageManager.extractRow(database, table, columns)
# storageManager.extractRow(database, table, columns)
# storageManager.extractRow(database, table, columns)
# storageManager.extractRow(database, table, columns)
# storageManager.extractRow(database, table, columns)
# storageManager.extractRow(database, table, columns)
# storageManager.extractRow(database, table, columns)
# j.extractRow('calificacion','loadCSV',[42663506])

#alterAddPK()

# storageManager.alterAddPK('database1','tab1',[])
# storageManager.alterAddPK('database2','table1',[])
# storageManager.alterAddPK('database3','table3',[])
# storageManager.alterAddPK('database4','table3',[])
# storageManager.alterAddPK('database5','table5',[])
# storageManager.alterAddPK('database6','table6',[])
# storageManager.alterAddPK('database7','table7',[])


#truncate()
# storageManager.dropTable('database1','tab1')
# storageManager.dropTable('database2','table_2')
# storageManager.dropTable('database3','table3')
# storageManager.dropTable('database4','table4')
# storageManager.dropTable('database5','table5')
# storageManager.dropTable('database6','table6')
# storageManager.dropTable('database7','table7')
